# docker/agent-whisper.Dockerfile
#
# Adds openai-whisper + preloaded 'small' weights on top of the stock agent
# runtime image, producing `wildclawbench-ubuntu:v1.4`.
#
# WHY this image exists
# ─────────────────────
# `environment/skills/audio-extract/scripts/transcribe.sh` walks a two-rung
# chain: the harness LiteLLM sidecar's /v1/audio/transcriptions route first,
# then a LOCAL openai-whisper fallback. The local rung is the only one that
# survives a keyless run: the sidecar's whisper route is registered ONLY when a
# whisper API key is present (`src/agents/openclaw/runner.py:601`), so on
# OAuth/Bedrock-only batches `WCB_AUDIO_TRANSCRIBE_URL` is legitimately unset
# and transcribe.sh has nowhere to go.
#
# Delivered bundles already get that local rung for free — their environment
# image is generated by `src/utils/harbor/dockerfile.py` (commit 59e84af),
# which bakes whisper + the 'small' weights into a `FROM ubuntu:24.04` build.
# Our OWN runtime image does not: `wildclawbench-ubuntu:v1.3` is a prebuilt
# ~28GB tarball distributed via HuggingFace (`script/run.sh:28`), with no
# Dockerfile in this repo that produces it. Nothing we can edit reaches it.
# Verified on the production host: `python3 -c "import whisper"` →
# ModuleNotFoundError, and transcribe.sh exits 3 on OAuth runs.
#
# So this Dockerfile is a thin additive layer that brings the runtime image to
# parity with what delivered bundles already ship. v1.3 stays untouched on
# disk; v1.4 is strictly v1.3 + whisper, and rollback is a one-line flip of
# AGENT_IMAGE in script/run.sh.
#
# The whisper stanza below is kept behaviorally identical to
# `src/utils/harbor/dockerfile.py` (same pip package, same 'small' model, same
# /opt/wb_whisper_models download_root, same /root/.cache/whisper symlink) so
# an agent's local rung behaves the same here as it does inside a bundle.
# `tests/test_agent_whisper_image.py` pins that parity.
#
# BUILD (normally automatic — `preflight_agent_image()` in script/run.sh runs
# this when the v1.4 tag is missing):
#   docker build -f docker/agent-whisper.Dockerfile -t wildclawbench-ubuntu:v1.4 .
# Needs internet (PyPI + the OpenAI weight CDN) and ~10–20 min, almost all of
# it torch. Nothing from the build context is COPYed in, so this builds from
# any checkout.
FROM wildclawbench-ubuntu:v1.3

# TWO deliberate deviations from the harbor recipe, both forced by the base:
#
# 1. No `--break-system-packages`. That flag is a pip 23.0+ response to PEP 668,
#    and harbor needs it because its `FROM ubuntu:24.04` base ships an
#    EXTERNALLY-MANAGED marker. v1.3 is Ubuntu 22.04.5 / Python 3.10.12 / pip
#    22.0.2: the flag does not exist there (`pip install --help` has no such
#    option, so passing it is a hard usage error) and there is no
#    EXTERNALLY-MANAGED marker to need it. Omitting it is the same install.
#
# 2. The proxy unset. v1.3 bakes `http_proxy`/`https_proxy=http://100.104.40.233:7897`
#    into its image env — a leftover from the original builder's corporate VPN
#    that is unroutable from Docker. Left in place, every outbound request in
#    this layer (PyPI, the weight CDN) dies against a dead proxy. The harness
#    already neutralizes this at RUN time by explicitly passing empty proxy
#    vars (see `src/utils/docker_utils.py:525`); we need the same at BUILD
#    time. `unset` inside the RUN is scoped to this one shell, so v1.4's
#    persisted image env stays byte-identical to v1.3's — deliberately, since
#    the runtime override is what production depends on and this image must not
#    quietly change it.
#
# Weights are preloaded at build time on purpose: agent containers run on an
# `--internal` Docker bridge with no egress (RUNBOOK.md §10 invariant #1), so a
# first-use download inside a task would hang, not fall back. `load_model` here
# both fetches small.pt into /opt/wb_whisper_models and proves the install
# imports, so a broken layer fails the BUILD instead of a trajectory.
#
# The symlink makes whisper's default cache location resolve to the same
# weights, so a caller that omits `download_root` (anything not going through
# transcribe.sh) also hits the baked file instead of attempting a download.
RUN unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY \
    && pip install --no-cache-dir openai-whisper \
    && mkdir -p /opt/wb_whisper_models \
    && python3 -c "import whisper; whisper.load_model('small', download_root='/opt/wb_whisper_models')" \
    && mkdir -p /root/.cache && ln -sfn /opt/wb_whisper_models /root/.cache/whisper

# iproute2 for `ss -K`: _break_stuck_llm_connections (runner.py:636-661) resets
# the container's wedged sockets to the sidecar, and v1.3 has no `ss` at all -
# every stall since has logged WCB_SS_UNAVAILABLE and done nothing. Placed
# AFTER the whisper RUN so the ~20-minute torch layer stays cached.
RUN unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY \
    && apt-get update && apt-get install -y --no-install-recommends iproute2 \
    && rm -rf /var/lib/apt/lists/*

# No CMD/ENTRYPOINT/ENV/WORKDIR override — everything else about the runtime
# contract (entrypoint, baked proxy env, workdir) is inherited unchanged from
# v1.3 so this image is a drop-in replacement.
